@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-end mb-2"><a class="btn btn-outline-primary" href="{{route('events.notifications',$event)}}">Notify Contributors</a></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<style>#add-contributor{min-width:112px}.collection-helper{font-size:.85rem}</style>
<div class="hero p-4 mb-4"><div class="d-flex justify-content-between"><div><p class="mb-1 text-uppercase small">Collection</p><h2 class="mb-1">{{$event->name}}</h2><p class="mb-0">{{$event->event_date->format('d M Y')}} · {{$event->venue}}</p></div><a class="btn btn-light align-self-center" target="_blank" href="{{route('events.collection.pdf',$event)}}">Print / PDF</a></div></div>
<div class="card p-4 mb-4"><div class="row align-items-end"><div class="col-md-5"><label class="form-label">Per-head amount</label><div class="input-group"><span class="input-group-text">₹</span><input id="per-head" class="form-control" type="number" step=".01" value="{{$event->per_head_amount}}" placeholder="Default for new contributors"><button id="save-per-head" class="btn btn-outline-primary">Save</button></div><small class="text-muted">Changes apply only to contributors added from now on.</small></div><div class="col-md-7"><label class="form-label">Add an active contributor</label><div class="input-group"><select id="contributor" class="form-select select2"><option value="">Select contributor</option>@foreach($available as $person)<option value="{{$person->id}}">{{$person->name}} · {{$person->phone}}</option>@endforeach</select><button id="add-contributor" class="btn btn-primary">Add</button></div></div></div></div>
<div class="card p-4"><h4>Collection list</h4><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Contributor</th><th>Contact</th><th>Due</th><th>Paid</th><th>Status</th><th>Paid date</th><th></th></tr></thead><tbody>@forelse($event->contributions as $row)<tr class="{{$row->contributor->status?'':'text-muted'}}"><td><strong>{{$row->contributor->name}}</strong>@if(!$row->contributor->status)<span class="badge text-bg-secondary ms-1">Inactive</span>@endif</td><td>{{$row->contributor->email}}<br><small>{{$row->contributor->phone}}</small></td><td>₹{{number_format($row->amount_due,2)}}</td><td>₹{{number_format($row->amount_paid,2)}}</td><td><span class="badge text-bg-{{$row->payment_status==='paid'?'success':($row->payment_status==='partial'?'warning':'danger')}}">{{ucfirst(str_replace('_',' ',$row->payment_status))}}</span></td><td>{{$row->paid_at?->format('d M Y') ?: '—'}}</td><td><button class="btn btn-sm btn-outline-primary pay" data-id="{{$row->id}}" data-paid="{{$row->amount_paid}}">Record payment</button>@if($row->amount_paid==0)<button class="btn btn-sm btn-link text-danger remove" data-id="{{$row->id}}">Remove</button>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No contributors added yet.</td></tr>@endforelse</tbody></table></div><div class="border-top pt-3 row"><div class="col"><small class="text-muted">Expected</small><strong class="d-block" id="expected">₹0.00</strong></div><div class="col"><small class="text-muted">Collected</small><strong class="d-block text-success" id="collected">₹0.00</strong></div><div class="col"><small class="text-muted">Outstanding</small><strong class="d-block" id="outstanding">₹0.00</strong></div><div class="col"><small class="text-muted">Paid / Partial / Unpaid</small><strong class="d-block" id="counts">0 / 0 / 0</strong></div></div></div>
<div class="modal fade" id="paymentModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Record payment</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input id="payment-id" type="hidden"><label>Amount paid</label><input id="payment-amount" class="form-control mb-3" type="number" step=".01"><label>Notes</label><textarea id="payment-notes" class="form-control"></textarea></div><div class="modal-footer"><button id="save-payment" class="btn btn-primary">Save payment</button></div></div></div></div>
<script>
const token='{{csrf_token()}}',base='{{route('events.collection',$event)}}',modal=new bootstrap.Modal(document.getElementById('paymentModal'));
const totalExpected={{$event->contributions->sum('amount_due')}}, totalCollected={{$event->contributions->sum('amount_paid')}}, totalPaid={{$event->contributions->where('payment_status','paid')->count()}}, totalPartial={{$event->contributions->where('payment_status','partial')->count()}}, totalUnpaid={{$event->contributions->where('payment_status','not_paid')->count()}};
const money=n=>'₹'+Number(n).toFixed(2); function showTotals(t){document.getElementById('expected').textContent=money(t.expected);document.getElementById('collected').textContent=money(t.collected);document.getElementById('outstanding').textContent=money(t.outstanding);document.getElementById('counts').textContent=t.paid+' / '+t.partial+' / '+t.not_paid;}
async function send(url,method,data){let r=await fetch(url,{method:method,headers:{'X-CSRF-TOKEN':token,'Accept':'application/json','Content-Type':'application/json'},body:data?JSON.stringify(data):null});let j=await r.json();if(!r.ok)throw new Error(j.message||'Request failed');return j;}
document.getElementById('save-per-head').onclick=async()=>{await send(base+'/per-head','PATCH',{per_head_amount:document.getElementById('per-head').value||null});alert('Per-head amount saved.');};
const picker=document.getElementById('contributor'),addButton=document.getElementById('add-contributor');if(picker.options.length>1){const allOption=document.createElement('option');allOption.value='__all__';allOption.textContent='Select all active contributors';picker.insertBefore(allOption,picker.options[1]);}const addGroup=addButton.parentNode;addGroup.parentNode.insertBefore(addButton,addGroup.nextSibling);addButton.classList.add('mt-2','px-4');addButton.onclick=async()=>{let id=picker.value;if(!id)return;addButton.disabled=true;addButton.textContent='Adding…';try{if(id==='__all__'){const ids=Array.from(picker.options).map(o=>o.value).filter(v=>/^\d+$/.test(v));await Promise.all(ids.map(contributor_id=>send(base,'POST',{contributor_id:contributor_id})));}else{await send(base,'POST',{contributor_id:id});}location.reload();}catch(error){alert(error.message);addButton.disabled=false;addButton.textContent='Add';}};
document.addEventListener('click',async e=>{if(e.target.classList.contains('pay')){document.getElementById('payment-id').value=e.target.dataset.id;document.getElementById('payment-amount').value=e.target.dataset.paid;modal.show();}if(e.target.classList.contains('remove')&&confirm('Remove this unpaid contributor?')){await send(base+'/'+e.target.dataset.id,'DELETE');location.reload();}});
document.getElementById('save-payment').onclick=async()=>{await send(base+'/'+document.getElementById('payment-id').value+'/payment','PATCH',{amount_paid:document.getElementById('payment-amount').value,notes:document.getElementById('payment-notes').value});location.reload();};
showTotals({expected:totalExpected,collected:totalCollected,outstanding:totalExpected-totalCollected,paid:totalPaid,partial:totalPartial,not_paid:totalUnpaid});
</script>
@endsection
